org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.vfs.watch=true
kotlin.incremental=false
kotlin.daemon.jvmargs=-Xmx2048M

android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
android.enableAarMetadataCheck=false
android.suppressUnsupportedCompileSdk=36
android.javaCompile.suppressSourceTargetDeprecationWarning=true
